name: power_ups
description: Different utilities to power ups your development.
version: 0.1.1
repository: https://github.com/alejandrogiubel/power_ups
homepage: https://github.com/alejandrogiubel/power_ups

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
